In [1]:
import sqlite3
import pandas as pd

In [2]:
def query(sql):
    con = sqlite3.connect("bleague/db.sqlite")
    return pd.read_sql_query(sql, con)

In [3]:
query("""
select distinct home from matches
""")

     home
0      島根
1      琉球
2     北海道
3    横浜BC
4      三河
5   FE名古屋
6    名古屋D
7     千葉J
8    SR渋谷
9      大阪
10     新潟
11     秋田
12     富山
13     広島
14     仙台
15     滋賀
16    宇都宮
17     群馬
18    A東京
19     信州
20     三遠
21     茨城
22     川崎
23     京都

In [4]:
df = query("""
select
  *
from
  matches
where
  home in ("横浜BC", "千葉J", "SR渋谷", "川崎", "A東京") and
  (
    home in ("横浜BC", "川崎") or
    away in ("横浜BC", "川崎")
  ) and
  dow in ("sun", "sat")
order by
  year, month, day
""")
df

     id  year  month  day  dow start_time  home away arena
0     4  2022     11   19  sat      15:05  横浜BC  A東京  横浜国プ
1    18  2022     11   20  sun      14:05  横浜BC  A東京  横浜国プ
2    55  2022     11   26  sat      15:05  横浜BC   新潟  横浜国プ
3    28  2022     11   27  sun      14:05  横浜BC   新潟  横浜国プ
4    85  2022     12    4  sun      20:05    川崎   島根  とどろき
5   153  2022     12   10  sat      15:05  横浜BC   三遠  横浜国プ
6    66  2022     12   11  sun      14:05  横浜BC   三遠  横浜国プ
7   102  2022     12   17  sat      16:05    川崎  宇都宮  とどろき
8   232  2022     12   24  sat      15:05  横浜BC   大阪  横浜国プ
9   240  2022     12   24  sat      19:05   千葉J   川崎    船橋
10  163  2022     12   25  sun      14:05  横浜BC   大阪  横浜国プ
11  165  2022     12   25  sun      15:05   千葉J   川崎    船橋
12  198  2022     12   31  sat      14:05  横浜BC   群馬  横浜国プ
13  204  2022     12   31  sat      16:05    川崎   京都  とどろき
14  108  2023      1    7  sat      14:05  横浜BC   琉球  横浜国プ
15  118  2023      1    7  sat      17:05   A東京   川崎  代々木一
16  137  2023      1    8  sun      14:05  横浜BC   琉球  横浜国プ
17  142  2023      1    8  sun      15:05   A東京   川崎  代々木一

In [5]:
for y, m, d, dow, s, h, a in zip(df.year, df.month, df.day, df.dow, df.start_time, df.home, df.away):
    print("%d-%02d-%02d %s %s〜 %s vs %s" % (y, m, d, "日" if dow == "sun" else "土", s, h, a))

2022-11-19 土 15:05〜 横浜BC vs A東京
2022-11-20 日 14:05〜 横浜BC vs A東京
2022-11-26 土 15:05〜 横浜BC vs 新潟
2022-11-27 日 14:05〜 横浜BC vs 新潟
2022-12-04 日 20:05〜 川崎 vs 島根
2022-12-10 土 15:05〜 横浜BC vs 三遠
2022-12-11 日 14:05〜 横浜BC vs 三遠
2022-12-17 土 16:05〜 川崎 vs 宇都宮
2022-12-24 土 15:05〜 横浜BC vs 大阪
2022-12-24 土 19:05〜 千葉J vs 川崎
2022-12-25 日 14:05〜 横浜BC vs 大阪
2022-12-25 日 15:05〜 千葉J vs 川崎
2022-12-31 土 14:05〜 横浜BC vs 群馬
2022-12-31 土 16:05〜 川崎 vs 京都
2023-01-07 土 14:05〜 横浜BC vs 琉球
2023-01-07 土 17:05〜 A東京 vs 川崎
2023-01-08 日 14:05〜 横浜BC vs 琉球
2023-01-08 日 15:05〜 A東京 vs 川崎

In [6]:
df = query("""
select
  *
from
  matches
where
  home = "SR渋谷" or away = "SR渋谷"
order by
  year, month, day
""")
df

     id  year  month  day  dow start_time  home   away arena
0     9  2022     11   19  sat      17:05  SR渋谷     茨城  青山学院
1    17  2022     11   20  sun      14:05  SR渋谷     茨城  青山学院
2    60  2022     11   26  sat      19:05  SR渋谷    北海道  青山学院
3    33  2022     11   27  sun      15:05  SR渋谷    北海道  青山学院
4    40  2022     11   30  wed      19:05  SR渋谷     三遠   墨田区
5   176  2022     12    3  sat      15:05    三河   SR渋谷  WA刈谷
6    80  2022     12    4  sun      15:05    三河   SR渋谷  WA刈谷
7   159  2022     12   10  sat      19:05  SR渋谷  FE名古屋  青山学院
8    71  2022     12   11  sun      15:05  SR渋谷  FE名古屋  青山学院
9   209  2022     12   14  wed      19:05    新潟   SR渋谷  アオーレ
10  104  2022     12   17  sat      17:05  SR渋谷     群馬  青山学院
11  186  2022     12   18  sun      14:05  SR渋谷     群馬  青山学院
12  237  2022     12   24  sat      17:05  SR渋谷     仙台  青山学院
13  162  2022     12   25  sun      14:05  SR渋谷     仙台  青山学院
14  221  2022     12   28  wed      19:05  SR渋谷   横浜BC  青山学院
15   92  2022     12   30  fri      15:05  名古屋D   SR渋谷  ドルアリ
16  203  2022     12   31  sat      15:05  名古屋D   SR渋谷  ドルアリ
17  117  2023      1    7  sat      15:05    京都   SR渋谷  京都市体
18  145  2023      1    8  sun      15:05    京都   SR渋谷  京都市体
19  126  2023      1   11  wed      19:05  SR渋谷     川崎   墨田区